# sudo: false
sudo: required
dist: trusty

language: python

python:
    - "2.7"
    #- "3.2"

virtualenv:
  system_site_packages: true

# install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install gmsh python-numpy
  - sudo apt-get -y install pandoc

install:
  - pip install -r requirements.txt
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .
  - pip install coverage

# run tests
script:
  - nosetests --with-coverage --cover-package=pygmsh

after_success:
  - bash <(curl -s https://codecov.io/bash)
