sudo: false
dist: trusty

language: python

python:
    - "2.7"
    # can't use anything higher than 3.4 with sudo :/
    - "3.4"

virtualenv:
  system_site_packages: true

addons:
  apt:
    sources:
    - sourceline: 'ppa:nschloe/gmsh-backports'
    - gmsh
    - pandoc
    #
    - python-numpy
    - python-scipy
    - python-matplotlib
    #
    - python3-numpy
    - python3-scipy
    - python3-matplotlib

# install dependencies
before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

# run tests
script:
  - cd test/ && pytest --cov=pygmsh

after_success:
  - bash <(curl -s https://codecov.io/bash)
